version: '3.8'

services:
  web:
    build:
      context: ./web
    volumes:
      - ./web:/code
    expose:
      - "8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: uwsgi --http 0.0.0.0:8000 --module myproject.wsgi

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - web
