version: '3.9'
services:
  web:
    build: .
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "myproject.wsgi:application"]
    volumes:
      - .:/code
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - web
