version: '3.8'

services:
  web:
    build:
      context: ./web
    volumes:
      - ./web:/code
    expose:
      - "8000"

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - web
